pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
        stages {
            stage('Checkout') {
                steps {
                    git branch: 'notifications',
                    url: ulator') {
                        sh './mvnw clean test'
                    }
                }
            }
        }
    }
}